schemaVersion: 2.3.0
metadata:
  name: jumpstarter-website-dev
  icon: https://jumpstarter.dev/jumpstarter.svg
  tags:
    - hugo
    - website
  language: Python
projects:
  - name: jumpstarter
    git:
      remotes:
        origin: https://github.com/jumpstarter-dev/website.git
components:
   - name: runtime
     container:
       image: quay.io/jumpstarter-dev/jumpstarter-website-devspace:latest
       mountSources: true
       memoryRequest: 1G
       memoryLimit: 4G
       cpuRequest: '1'
       cpuLimit: '2'

commands:
  - id: serve-website
    exec:
      component: runtime
      commandLine: "cd website && hugo serve --bind 0.0.0.0"
