- name: "Test Jetson kmods"
  tags:
    - orin
  expect-timeout: 60
  tasks:
    - name: "Power off"
      power:
        action: off
    - name: "Load image"
      set-disk-image:
        image: "rhel-guest-image.raw"

    - name: "Attach storage"
      storage:
        attached: true

    - name: "Power on"
      power:
        action: on

    - expect:
        this: "login: "
        debug_escapes: false
        timeout: 300
    - send:
        this:
          - "root\n"
          - "redhat\n"
    - pause:
        seconds: 3
    - expect:
        debug_escapes: false
        this: "[root@localhost ~]#"
    - send:
        echo: true
        this:
          - "sudo dnf update -y\n"
    - expect:
        timeout: 120
        echo: true
        debug_escapes: false
        this: "Complete"
    - expect:
        debug_escapes: false
        this: "[root@localhost ~]#"

    - send:
        echo: true
        this:
          - "sudo dnf install -y nvidia-jetpack-kmod\n"
    - expect:
        timeout: 120
        echo: true
        debug_escapes: false
        this: "Complete"

    - send:
        debug_escapes: false
        this:
          - "reboot\n"

    - expect:
        this: "login: "
        debug_escapes: false
        timeout: 500 # the kmod boot takes very long because of some issues with the crypto modules from nvidia
    - send:
        this:
          - "root\n"
          - "redhat\n"

    - send:
        echo: false # we dont want to capture any of the output so expect will catch it
        this:
          - "\n"
          - "\n"
    - expect:
        debug_escapes: false
        echo: true
        this: "[root@localhost ~]#"

    - send:
        echo: false # we dont want to capture any of the output so expect will catch it
        this:
          - "lsmod | grep --color=never nv\n"


    - expect:
        echo: true
        this: "nvgpu"

    - write-ansible-inventory:
        filename: "inventory.yaml"
        ssh_key: ~/.ssh/id_rsa
    - local-shell:
        script: |
          ansible -m ping -i inventory.yaml all

 cleanup:
   - send:
       debug_escapes: false
       this:
         - "poweroff\n"
   - pause:
       seconds: 5

   - name: "Power off"
     power:
       action: off
   - name: "Detach storage"
     storage:
       connected: false

