- name: "Test Jetson kmods"
  tags:
    - xavier-nx
    - 8gb
  expect-timeout: 60
  tasks:
    - name: "Power off"
      power:
        action: off
    - name: "Load image"
      set-disk-image:
        image: "isos/RHEL-9.3.0-20230809.27-aarch64-boot.iso"

    - name: "Attach storage"
      storage:
        attached: true

    - name: "Power on"
      power:
        action: on

    - expect:
        this: "F11   to enter Boot Manager Menu."
        send: "<ENTER>"
        echo: true
        debug_escapes: true

    - expect:
        this: "GRUB version"
        send: "<ENTER>"
        echo: true
        debug_escapes: true

    - expect:
        this: "forever"
        echo: true

    - send:
        this:
          - "e"
          - "<DOWN>"
          - "<DOWN>"
          - "<CTRL-E>"
          - "inst.vnc console=ttyS0,115200"
          - "<ENTER>"

    - uefi-go-to:
        option: "Boot Manager"
    - uefi-go-to:
        option: "UEFI {{ StorageName }}" # find ansible variable insertion

    - expect:
        this: "GRUB version"
        send: "<up-arrow>e<down-arrow><down-arrow><CTRL-E> inst.ks=...."

    - expect:
        this: "Install finished"

    - name: "Detach storage"
      storage:
        connected: false

    - login-and-get-inventory:
        user: "root"
        password: "{{ env.password }}"
        inventory: "inventory.json"

    - ansible_playbook:
        playbook: test-kmods.yaml
        inventory: "inventory.json"
        extra_args:

